# -*- coding:utf-8 -*-
# dir definition 
SDK_BIN_DIR := $(SDK_INSTALL_DIR)/bin
SDK_BUILD_DIR=$(SDK_INSTALL_DIR)/build
SDK_ETC_DIR := $(SDK_INSTALL_DIR)/etc
SDK_SRC_REPO_DIR := $(SDK_INSTALL_DIR)/src
SDK_PATCHES_DIR := $(SDK_INSTALL_DIR)/patches
SDK_LOG_DIR := $(SDK_INSTALL_DIR)/logs
SDK_OUTPUT_DIR := $(SDK_INSTALL_DIR)/output
SDK_PREBUILD_DIR := $(SDK_INSTALL_DIR)/prebuild
#SDK_VALIDATION_DIR := $(SDK_INSTALL_DIR)/validation
#SDK_TEMPLATES_DIR := $(SDK_INSTALL_DIR)/templates
#SDK_IMAGES_DIR := $(SDK_PREBUILD_DIR)/images

SDK_MK_COMPONENTS_DIR := $(SDK_MK_DIR)/components
SDK_MK_BOARDS_DIR := $(SDK_MK_DIR)/boards
SDK_MK_DISTROS_DIR := $(SDK_MK_DIR)/distros

SDK_KCONDIFLIB_DIR := $(SDK_MK_DIR)/Kconfiglib

SDK_CONFIGS_DIR := $(SDK_ETC_DIR)
SDK_BOARD_CONFIGS_DIR := $(SDK_CONFIGS_DIR)/boards

