# -*- coding:utf-8 -*-
## toolchain

ifeq ($(CONFIG_WITH_SYSTEM_CROSS_COMPILE),y)
CROSS_COMPILE := $(CONFIG_SYSTEM_CROSS_COMPILE)
endif

ifeq ($(CONFIG_WITH_EXTERNAL_CROSS_COMPILE),y)
CROSS_COMPILE := $(CONFIG_EXTERNAL_CROSS_COMPILE)
endif

CROSS_COMPILE_ENV := ARCH=$(CONFIG_ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

ifeq ($(CONFIG_WITH_EXTERNAL_CROSS_COMPILE),y)
CROSS_COMPILE_ENV += PATH=$(CONFIG_EXTERNAL_CROSS_COMPILE_DIR):$${PATH}
endif
